mdata<-read.delim("data/farray.txt",as.is=T,header=T)
stressdata<-read.delim("data/stress.txt",as.is=T,header=T)
sid<-read.delim("data/sid.txt",as.is=T,header=T)
path<-read.delim("data/path.txt",as.is=T,header=T)
metapath<-read.delim("data/metapath.txt",as.is=T,header=T)
fs <- readDNAStringSet("NC_000911.fna", "fasta")
sgo<-read.delim("data/gosyn.txt",as.is=T,header=T)
id<-read.delim("data/id.txt",as.is=T,header=T)
syn<-read.delim("data/sid.txt",as.is=T,header=T)
seg<-read.delim("data/seg.txt",as.is=T,header=F)
dataall <- read.delim("data/dataalln.txt", as.is=T, header=T)
interact <- read.delim("data/interactome.txt", as.is=T, header=T)
cogc <- read.delim("data/syncogclr.txt", as.is=T, header=T)
kasc <- read.delim("data/kasuzaclr.txt", as.is=T, header=T)
kar <-subset(dataall,dataall[,2]=="gene")
tata <-subset(dataall,dataall[,2]=="TATA")
asrna <-subset(dataall,dataall[,2]=="asRNA")
tp <-subset(dataall,dataall[,2]=="TP")
tpr <-read.delim("data/promo.txt", as.is=T, header=T)
ncrna <-subset(dataall,dataall[,2]=="ncRNA")
utr <-subset(dataall,dataall[,2]=="5'UTR")
p1 <-subset(dataall,dataall[,2]=="hip1")
intern <-subset(dataall,dataall[,2]=="intern")
trunit <- read.delim("data/trunit.txt", as.is=T, header=T)
